language: java

jdk:
  - oraclejdk7

before_script:
  - sleep 15
  - mongo gfk --eval 'db.addUser("gfk", "password");'

install:
  - gradle clean build -Pdb.uri=mongodb://localhost/gfk -Pdb.username=gfk -Pdb.password=password