language: java

jdk:
  - oraclejdk7

env:
  - TERM=dumb

services:
  - mongodb

before_script:
  - sleep 15
  - mongo gfk --eval 'db.addUser("gfk", "password");'

after_success:
  - gradle cobertura coveralls

before_install:
  - chmod +x gradlew